feat add isTruthy and isFalsey helpers
Oneflow/handlebars-kit pull request #12
Opened 2021-09-02 10:38 UTC by Sergio-svb

## Context
https://hpinc.kanbanize.com/ctrl_board/49/cards/14048/details/
https://github.com/oneflow/siteflow-api/pull/2402

2021-09-02 10:39 UTC, oneflow-build commented
Congrats! The repository doesn't have any security vulnerability issues.

2021-09-02 11:02 UTC, thekiwi requested changes

2021-09-02 11:02 UTC, thekiwi commented on lib/utils/index.js
> +const falsey = require('falsey');
I spent a lot of time reducing the number of dependencies this library has to zero. Can we please do the same here?

2021-09-02 14:36 UTC, joseandrespg commented on lib/utils/index.js
> +    return keywords.includes(value) || keywords.includes(value.toLowerCase);
```suggestion
    return keywords.includes(value) || keywords.includes(value.toLowerCase());
```

2021-09-02 14:47 UTC, joseandrespg commented on lib/comparison.js
> + * Returns true if the given `value` is falsey. Uses the [falsey][]
Update the js docs falsey references

2021-09-02 15:33 UTC, joseandrespg approved these changes

2021-09-02 16:00 UTC, merged

2021-09-07 16:21 UTC, oneflow-build commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/oneflow/handlebars-kit/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: