fix: forEach and forOwn helpers
Oneflow/handlebars-kit pull request #16
Opened 2021-09-22 13:14 UTC by Sergio-svb

## Context
https://hpinc.kanbanize.com/ctrl_board/55/cards/14614/details/

2021-09-22 13:14 UTC, oneflow-build commented
Congrats! The repository doesn't have any security vulnerability issues.

2021-09-22 14:21 UTC, juanjoseruiz approved these changes

2021-09-22 15:16 UTC, joseandrespg approved these changes

2021-09-27 14:45 UTC, thekiwi requested changes

2021-09-27 14:45 UTC, thekiwi commented on package.json
>    "publishConfig": {
we need to remove publishConfig also

2021-09-27 16:59 UTC, Sergio-svb commented
the test coverage is fixed now

2021-09-27 17:01 UTC, thekiwi approved these changes

2021-09-27 17:20 UTC, merged

2021-09-27 17:21 UTC, oneflow-build commented
:tada: This PR is included in version 1.2.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/handlebars-kit)
- [GitHub release](https://github.com/oneflow/handlebars-kit/releases/tag/v1.2.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: