fix: update vulnerable dependencies
Oneflow/handlebars-kit pull request #22
Opened 2021-09-29 15:32 UTC by Sergio-svb

- update vulnerable dependencies
- update readme

2021-09-29 15:32 UTC, oneflow-build commented
It seems like your PR fixes one of the security vulnerability issues. Good job!

2021-09-30 07:44 UTC, joseandrespg approved these changes

2021-09-30 08:42 UTC, thekiwi requested changes

2021-09-30 08:42 UTC, thekiwi commented on README.md
> +This is a fork of the [handlebars-kit](https://github.com/helpers/handlebars-helpers) created by [Jon Schlinkert](https://github.com/jonschlinkert).
```suggestion
This is a fork of the [handlebars-helpers](https://github.com/helpers/handlebars-helpers) created by [Jon Schlinkert](https://github.com/jonschlinkert).
```

It's a fork of `handlebars-helpers` not `handlebars-kit`

2021-09-30 08:42 UTC, thekiwi commented on README.md
>  # NOTE: WIP FORK
```suggestion
# Handlebars Kit

More than 150 helpers in ~15 categories designed to extend the Node.js Handlebars library.
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
> +- The fork has higher test coverage
```suggestion
Motivations for forking
- To minimise the number of dependencies, reducing the maintenance effort
- To remove potentially risky helpers (such as any that interact with the file system)
- To increase the number of test cases and resulting test coverage
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
>  > More than 130 Handlebars helpers in ~20 categories. Helpers can be used with Assemble, Generate, Verb, Ghost, gulp-handlebars, grunt-handlebars, consolidate, or any node.js/Handlebars project.
```suggestion
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
> +var helpers = require('handlebars-kit')();
```suggestion
const helpers = require('handlebars-kit')();
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
>  var math = helpers.math();
```suggestion
const helpers = require('handlebars-kit');
const math = helpers.math();
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
>  var array = helpers.array();
```suggestion
const helpers = require('handlebars-kit');
const array = helpers.array();
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
> +var helpers = require('handlebars-kit')(['math', 'string']);
```suggestion
const helpers = require('handlebars-kit')(['math', 'string']);
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
> +var helpers = require('handlebars-kit')({
```suggestion
const helpers = require('handlebars-kit')({
```

2021-09-30 08:42 UTC, thekiwi commented on README.md
>  * **[after](#after)** ([code](lib/array.js#L22) | [tests](test/array.js#L13))
Are these links to the code line numbers (ie, `lib/array.js#13`) still correct, or have they changed since the fork/refactoring?

2021-10-04 12:53 UTC, thekiwi approved these changes

2021-10-04 13:34 UTC, merged

2021-10-04 13:36 UTC, oneflow-build commented
:tada: This PR is included in version 1.2.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/handlebars-kit/v/1.2.3)
- [GitHub release](https://github.com/oneflow/handlebars-kit/releases/tag/v1.2.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: