fix: add moment timezone to formatDate helper
Oneflow/handlebars-kit pull request #33
Opened 2022-08-11 21:23 UTC by jim-peng

Kanbanize Card: https://hpinc.kanbanize.com/ctrl_board/55/cards/18885/details/ 

**Change:**
- Add param in formatDate to change the timezone for the date

**Reason:**
There is a discrepancy between the dates that would be shown via the Greensheet timezone vs the order details/batch details due to the latter formatting the dates to the account settings timezone while the greensheet uses the handlebar helper that always sets the time to UTC.

2022-08-11 21:23 UTC, oneflow-build commented
Your PR is blocked because this repository has 24 security vulnerabillity issue(s) with critical or high severity:

- [eslint-utils](https://github.com/advisories/GHSA-3gx7-xhv7-5mx3/dependabot) (CRITICAL severity). PR created by dependabot: https://github.com/oneflow/handlebars-kit/pull/25
- [handlebars](https://github.com/advisories/GHSA-w457-6q6x-cgp9/dependabot) (CRITICAL severity). PR created by dependabot: https://github.com/oneflow/handlebars-kit/pull/24
- [minimist](https://github.com/advisories/GHSA-xvch-5gv4-984h/dependabot) (CRITICAL severity). PR created by dependabot: none
- [lodash](https://github.com/advisories/GHSA-jf85-cpcp-j695/dependabot) (CRITICAL severity). PR created by dependabot: none
- [json-schema](https://github.com/advisories/GHSA-896r-f27r-55mw/dependabot) (CRITICAL severity). PR created by dependabot: none
- [acorn](https://github.com/advisories/GHSA-6chw-6frg-f759/dependabot) (HIGH severity). PR created by dependabot: https://github.com/oneflow/handlebars-kit/pull/26
- [marked](https://github.com/advisories/GHSA-5v2h-r2cx-5xgj/dependabot) (HIGH severity). PR created by dependabot: none
- [moment](https://github.com/advisories/GHSA-8hfj-j24r-96c4/dependabot) (HIGH severity). PR created by dependabot: https://github.com/oneflow/handlebars-kit/pull/32
- [node-fetch](https://github.com/advisories/GHSA-r683-j2x4-v87g/dependabot) (HIGH severity). PR created by dependabot: https://github.com/oneflow/handlebars-kit/pull/29
- [ansi-regex](https://github.com/advisories/GHSA-93q8-gq69-wqmw/dependabot) (HIGH severity). PR created by dependabot: none
- [npm](https://github.com/advisories/GHSA-hj9c-8jmm-8c52/dependabot) (HIGH severity). PR created by dependabot: none

To unblock your PR you must fix security issues with CRITICAL or HIGH severity.

If there's no dependabot PR to fix the issue yet and you're planning on fixing it, make sure to include `bump {packageName}` into your commit message.

If you already fixed this issue in a different PR, please merge your branch with the default repo branch to unblock it.

If you already fixed the issue in this PR but didn't include `bump {packageName}` into your commit message, please edit the PR title or body so it includes `bump {packageName}` or `update vulnerable dependencies`. This will trigger the action again and will unblock the PR.

2022-08-12 05:46 UTC, Sergio-svb requested changes

2022-08-12 05:46 UTC, Sergio-svb commented on package.json
> +    "moment-timezone": "^0.5.34"
should be added to peerDependencies

2022-08-12 14:10 UTC, clouthier commented
Are these critical and high vulnerabilities going to be addressed?  Not all the outstanding PRs entered by the bot need to be done because some are low and medium.  but the Critical and High should be addressed.  @Sergio-svb what do you think?

2022-08-12 14:17 UTC, Sergio-svb commented
@clouthier yes all critical and high vulnerabilities should be resolved

2022-08-15 14:09 UTC, prwissen approved these changes

2022-08-16 14:26 UTC, jim-peng commented
Separate PR / branch being made to look into fixing all the high and critical vulnerabilities

2022-08-17 14:54 UTC, Sergio-svb approved these changes

2022-08-18 18:28 UTC, merged

2022-08-18 18:30 UTC, oneflow-build commented
:tada: This PR is included in version 1.2.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/handlebars-kit/v/1.2.4)
- [GitHub release](https://github.com/oneflow/handlebars-kit/releases/tag/v1.2.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: